## Settings
title: 0xF00D
owner: "Milton Candelero"
url: "https://miltoncandelero.github.io/0xF00D"
baseurl: "/"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "miltoncandelero@gmail.com"
github: "miltoncandelero/0xF00D"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "All Chicken Right Wings and Chicken Left Wings well fried and crispy."
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
